name: scan-images

on:
  schedule:
    - cron: "0 12 * * 1"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  scan:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # tag=v3.1.0
    - name: Setup go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # tag=v5.1.0
      with:
        go-version: 1.21
    - name: Run verify container script
      run: make verify-container-images
